### ISSUE TITLE
Flush the log 

### ISSUE THREAD

**Issue by FlominatorTM** [Linekio/getmyancestors#12]
It's cool that getmyancestors.py offers writing a log file. Unfortunately I can't use it for progress control ("are you still doing something or did you just get stuck?") because it apparently only writes the log on disk at the end of the process. Would it be possible to have the log written after every step or something like that?

**Comment by Linekio** [comment]
I think the only way to do that is to close the file and re-open it for each line to write, but I don't like the idea.
I think the best option (for CLI mode) is to modify -v and -l option.
Actually:
-v : print in cli
-l : nothing
-v -l : print in log file

I'll change to:
-v : print in the cli
-l : print in the log file
-v + -l : both

Actually:
-v : print in cli
-l : nothing
-v + -l : print in log file

**Comment by FlominatorTM** [comment]
Oh, I though -v was for "verbose logging". In the end I don't need a log, so using -v without -l did the trick for me. But making -v + -l work for both sounds like a good idea.

**Comment by Linekio** [comment]
Closes with 72a0971320515e371ac2592652cc1d5d68d04a82
