### ISSUE TITLE
Duplicate family memberships

### ISSUE THREAD

**Issue by FlominatorTM** [Linekio/getmyancestors#16]
Hi there,

the file [ungarn.ged.txt](https://github.com/Linekio/getmyancestors/files/3257724/ungarn.ged.txt) has a lot of duplicate family memberships. See for example line 19 and 20:

> 1 FAMS @F1@
> 1 FAMS @F1@

I used this line with c06fc5fb9bc4455d74cd26ab6d856287769ef68b to create the file:

> python getmyancestors.py -a 20 -d 25 -m -u my_user -p my_password -i LYNH-CQB -o ungarn.ged -v

Thanks in advance

Flo

**Comment by Linekio** [comment]
Thanks for the report, it's probably a mistake I forgot when I reformatted the code.
Closed with https://github.com/Linekio/getmyancestors/commit/78b1ed36c61de567b653d7cee2d98c647785d738
