### ISSUE TITLE
fstogedcom.py no attribute error

### ISSUE THREAD

**Issue by athey3** [Linekio/getmyancestors#17]
./fstogedcom.py 
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./fstogedcom.py", line 464, in login
    self.fs.get_url("/platform/tree/persons/%s/ordinances.json" % self.fs.get_userid())
AttributeError: 'Session' object has no attribute 'get_userid'

**Comment by athey3** [comment]
Error is actually in getmyancestors.py routine so the error is likely something being referenced from fstogedcom incorrectly

**Comment by athey3** [comment]
Error is actually in one of the included routines so the error is likely something being referenced from fstogedcom incorrectly

**Comment by Linekio** [comment]
Closed with https://github.com/Linekio/getmyancestors/commit/323ac78f95099f510dca800e9a303097844f1b9d
