### ISSUE TITLE
Missing ordinance

### ISSUE THREAD

**Issue by sebdu66** [Linekio/getmyancestors#19]
The initiatory ordinance is missing.

I add this at the line 636 :
elif o["type"] == "http://lds.org/Initiatory":
      self.initiatory = Ordinance(o)

So for my needs it's working, but I think there need to have more change to integrate it in the gedcom

**Comment by Linekio** [comment]
There is no GEDCOM tag for initiatory :
[https://www.tamurajones.net/GEDCOMTags.xhtml](https://www.tamurajones.net/GEDCOMTags.xhtml)

**Comment by sebdu66** [comment]
I believe that the tag is 
WAC | Washing And Clothing.

From this source
https://www.gedcompublisher.com/en/tag-types.htm
WAC	Other	LDS Initiation

I will need to test with the PAF software to export to gedcom to see if it's really this one.

**Comment by sebdu66** [comment]
I try PAF 4 and PAF 5 and they didn't have the option to add an initiatory.
I try with rootsmagic and we can add it.
I just created a test person and add only an iniatory to him then I export it to gedcom.
I don't know how to read a gedcom ;)
I see a WAC tag and the date that I put, 2 FEB 2019

Here is the result of the gedcom: 

`0 HEAD
1 SOUR RootsMagic
2 NAME RootsMagic
2 VERS 7.5.9.0
2 CORP RootsMagic, Inc.
3 ADDR PO Box 495
4 CONT Springville, UT 84663
4 CONT USA
3 PHON 1-800-ROOTSMAGIC
3 WWW www.RootsMagic.com
1 DEST RootsMagic
1 DATE 16 JUL 2019
1 FILE testt.ged
1 GEDC
2 VERS 5.5.1
2 FORM LINEAGE-LINKED
1 CHAR UTF-8
0 @I1@ INDI
1 NAME test /test/
2 GIVN test
2 SURN test
1 SEX M
1 _UID 595AAB7C434745F5840945D60124A0636E3A
1 CHAN
2 DATE 16 JUL 2019
1 WAC
2 DATE 2 FEB 2019
2 STAT Completed
2 TEMP SWISS
0 _EVDEF BIRT
1 TYPE P
1 TITL Birth
1 ABBR Birth
1 SENT [person] was born< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the birth of [person]< [Date]>< [PlaceDetails]>< [
3 CONC Place]>.
1 ROLE Doctor
2 SENT [ThisPerson] delivered [person]< [Date]>< [PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF DEAT
1 TYPE P
1 TITL Death
1 ABBR Death
1 SENT [person] died< [Desc]>< [Date]>< [person:Age]>< [PlaceDetails]>< [Place
2 CONC ]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the death of [person]< [Date]>< [PlaceDetails]>< [
3 CONC Place]>.
1 PLAC Y
1 DATE Y
1 DESC Y
0 _EVDEF CHR
1 TYPE P
1 TITL Christen
1 ABBR Chr
1 SENT [person] was christened< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the christening of [person]< [Date]>< [PlaceDeta
3 CONC ils]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF BURI
1 TYPE P
1 TITL Burial
1 ABBR Burial
1 SENT [person] was buried< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the burial of [person]< [Date]>< [PlaceDetails]>
3 CONC < [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF CREM
1 TYPE P
1 TITL Cremation
1 ABBR Cremation
1 SENT [person] was cremated< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the cremation of [person]< [Date]>< [PlaceDetail
3 CONC s]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF ADOP
1 TYPE P
1 TITL Adoption
1 ABBR Adoption
1 SENT [person] was adopted< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the adoption of [person]< [Date]>< [PlaceDetails
3 CONC ]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF BAPM
1 TYPE P
1 TITL Baptism
1 ABBR Baptism
1 SENT [person] was baptized< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the baptism of [person]< [Date]>< [PlaceDetails]
3 CONC >< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF BARM
1 TYPE P
1 TITL Bar Mitzvah
1 ABBR Bar Mitzvah
1 SENT [person] celebrated his bar mitzvah< [Date]>< [PlaceDetails]>< [Place]>
2 CONC .
1 ROLE Witness
2 SENT [ThisPerson] witnessed the bar mitzvah of [person]< [Date]>< [PlaceDeta
3 CONC ils]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF BASM
1 TYPE P
1 TITL Bas Mitzvah
1 ABBR Bas Mitzvah
1 SENT [person] celebrated her bas mitzvah< [Date]>< [PlaceDetails]>< [Place]>
2 CONC .
1 ROLE Witness
2 SENT [ThisPerson] witnessed the bas mitzvah of [person]< [Date]>< [PlaceDeta
3 CONC ils]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF BLES
1 TYPE P
1 TITL Blessing
1 ABBR Blessing
1 SENT [person] was blessed< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the blessing of [person]< [Date]>< [PlaceDetails
3 CONC ]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF CHRA
1 TYPE P
1 TITL Christen (adult)
1 ABBR Chr (adult)
1 SENT [person] was christened< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the christening of [person]< [Date]>< [PlaceDeta
3 CONC ils]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF CONF
1 TYPE P
1 TITL Confirmation
1 ABBR Confirmation
1 SENT [person] was confirmed< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the confirmation of [person]< [Date]>< [PlaceDet
3 CONC ails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF FCOM
1 TYPE P
1 TITL First communion
1 ABBR First comm
1 SENT [person] received first communion< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the first communion of [person]< [Date]>< [Place
3 CONC Details]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF ORDN
1 TYPE P
1 TITL Ordination
1 ABBR Ordination
1 SENT [person] was ordained< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the ordination of [person]< [Date]>< [PlaceDetai
3 CONC ls]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF NATU
1 TYPE P
1 TITL Naturalization
1 ABBR Naturalization
1 SENT [person] was naturalized< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the naturalization of [person]< [Date]>< [PlaceD
3 CONC etails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF EMIG
1 TYPE P
1 TITL Emigration
1 ABBR Emigration
1 SENT [person] emigrated< [Date]>< from [Place:plain]>< [PlaceDetails]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the emigration of [person]< [Date]>< [PlaceDetai
3 CONC ls]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF IMMI
1 TYPE P
1 TITL Immigration
1 ABBR Immigration
1 SENT [person] immigrated< [Date]>< to [Place:plain]>< [PlaceDetails]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the immigration of [person]< [Date]>< [PlaceDeta
3 CONC ils]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF CENS
1 TYPE P
1 TITL Census
1 ABBR Census
1 SENT [person] appeared in the census< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] appeared in the household of [person] in the census< [Date
3 CONC ]>< [PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF PROB
1 TYPE P
1 TITL Probate
1 ABBR Probate
1 SENT [person] had [person:hisher] estate probated< [Date]>< [PlaceDetails]>< [
2 CONC Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the probate of [person]< [Date]>< [PlaceDetails]
3 CONC >< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF WILL
1 TYPE P
1 TITL Will
1 ABBR Will
1 SENT [person] signed a will< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the will of [person]< [Date]>< [PlaceDetails]>< [
3 CONC Place]>.
1 ROLE Heir
2 SENT [ThisPerson] was named an heir in the will of [person]< [Date]>< [Place
3 CONC Details]>< [Place]>.
1 ROLE Executor
2 SENT [ThisPerson] was named an executor for the will of [person]< [Date]>< [
3 CONC PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF GRAD
1 TYPE P
1 TITL Graduation
1 ABBR Graduation
1 SENT [person] graduated< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the graduation of [person]< [Date]>< [PlaceDetai
3 CONC ls]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF RETI
1 TYPE P
1 TITL Retirement
1 ABBR Retirement
1 SENT [person] retired< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the retirement of [person]< [Date]>< [PlaceDetai
3 CONC ls]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF DSCR
1 TYPE P
1 TITL Description
1 ABBR Description
1 SENT [person] was described as [Desc]< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the appearance of [person] as [Desc]< [Date]>< [
3 CONC PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC Y
0 _EVDEF EDUC
1 TYPE P
1 TITL Education
1 ABBR Education
1 SENT [person] was educated < [Desc]>< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the education of [person]< [Date]>< [PlaceDetail
3 CONC s]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC Y
0 _EVDEF NATI
1 TYPE P
1 TITL Nationality
1 ABBR Nationality
1 SENT [person] was [Desc]< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the nationality of [person] as [Desc]< [Date]>< [
3 CONC PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC Y
0 _EVDEF OCCU
1 TYPE P
1 TITL Occupation
1 ABBR Occupation
1 SENT [date] [person] was [Desc:A]< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the occupation of [person]< [Date]> as [Desc:A]< [
3 CONC PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC Y
0 _EVDEF PROP
1 TYPE P
1 TITL Property
1 ABBR Property
1 SENT [person] owned [Desc]< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the property of [person] as [Desc:A]< [Date]>< [
3 CONC PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC Y
0 _EVDEF RELI
1 TYPE P
1 TITL Religion
1 ABBR Religion
1 SENT [person] was [Desc]< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the religion of [person] as [Desc:A]< [Date]>< [
3 CONC PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC Y
0 _EVDEF RESI
1 TYPE P
1 TITL Residence
1 ABBR Residence
1 SENT [person] lived< [Desc]>< [PlaceDetails]>< [Place]>< [Date]>.
1 ROLE Witness
2 SENT [ThisPerson] lived in the residence of [person] < [PlaceDetails]>< [Pla
3 CONC ce]>< [Date]>.
1 PLAC Y
1 DATE Y
1 DESC Y
0 _EVDEF SSN
1 TYPE P
1 TITL Soc Sec No
1 ABBR SSN
1 SENT [person] had Social Security Number [Desc].
1 PLAC N
1 DATE N
1 DESC Y
0 _EVDEF BAPL
1 TYPE P
1 TITL LDS Baptism
1 ABBR LDS Bapt
1 SENT [person] was baptized into the LDS Church< [Date]>< [PlaceDetails]>< [P
2 CONC lace]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the baptism of [person] into the LDS Church< [Da
3 CONC te]>< [PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF ENDL
1 TYPE P
1 TITL LDS Endowment
1 ABBR LDS Endow
1 SENT [person] was endowed< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the endowment of [person]< [Date]>< [PlaceDetail
3 CONC s]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF SLGC
1 TYPE P
1 TITL LDS Seal to parents
1 ABBR LDS SealPar
1 SENT [person] was sealed to [person:hisher] parents< [Date]>< [PlaceDetails]
2 CONC >< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the sealed to parents of [person]< [Date]>< [Pla
3 CONC ceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF AFN
1 TYPE P
1 TITL Ancestral File Number
1 ABBR AFN
1 SENT [person] has Ancestral File Number [Desc].
1 PLAC N
1 DATE N
1 DESC Y
0 _EVDEF REFN
1 TYPE P
1 TITL Reference No
1 ABBR Ref #
1 SENT [person] has reference number [Desc].
1 PLAC N
1 DATE N
1 DESC Y
0 _EVDEF CAST
1 TYPE P
1 TITL Caste
1 ABBR Caste
1 SENT [person] was associated with [Desc]< [Date]>< [PlaceDetails]>< [Place]>
2 CONC .
1 ROLE Witness
2 SENT [ThisPerson] witnessed the associated with [Desc] of [person]< [Date]>< [
3 CONC PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC Y
0 _EVDEF TITL
1 TYPE P
1 TITL Title (Nobility)
1 ABBR Title
1 SENT [person] held the title of [Desc]< [Date]>< [PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC Y
0 _EVDEF CONL
1 TYPE P
1 TITL LDS Confirmation
1 ABBR LDS Conf
1 SENT [person] was confirmed a member of the LDS Church< [Date]>< [PlaceDetai
2 CONC ls]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the confirmation of [person] as a member of the L
3 CONC DS Church< [Date]>< [PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF WAC
1 TYPE P
1 TITL LDS Initiatory
1 ABBR LDS Init
1 SENT [person] received LDS initiatory< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the LDS initiatory of [person]< [Date]>< [PlaceD
3 CONC etails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF MARR
1 TYPE F
1 TITL Marriage
1 ABBR Marriage
1 SENT [couple] <#Couple#was|were> married< [Date]>< [PlaceDetails]>< [Place]>
2 CONC .
1 ROLE Witness
2 SENT [ThisPerson] witnessed the marriage of [couple]< [Date]>< [PlaceDetails
3 CONC ]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF ANUL
1 TYPE F
1 TITL Annulment
1 ABBR Annulment
1 SENT [couple] had their marriage annulled< [Date]>< [PlaceDetails]>< [Place]
2 CONC >.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the annulment of the marriage of [couple]< [Date
3 CONC ]>< [PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF DIV
1 TYPE F
1 TITL Divorce
1 ABBR Divorce
1 SENT [couple] <#Couple#was|were> divorced< [Date]>< [PlaceDetails]>< [Place]
2 CONC >.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the divorce of [couple]< [Date]>< [PlaceDetails]
3 CONC >< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF DIVF
1 TYPE F
1 TITL Divorce filed
1 ABBR Div. filed
1 SENT [couple] filed for divorce< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the divorce filing of [couple]< [Date]>< [PlaceD
3 CONC etails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF ENGA
1 TYPE F
1 TITL Engagement
1 ABBR Engagement
1 SENT [couple] <#Couple#was|were> engaged< [Date]>< [PlaceDetails]>< [Place]>
2 CONC .
1 ROLE Witness
2 SENT [ThisPerson] witnessed the engagement of [couple]< [Date]>< [PlaceDetai
3 CONC ls]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF MARB
1 TYPE F
1 TITL Marriage Bann
1 ABBR Marr Bann
1 SENT [couple] had marriage banns published< [Date]>< [PlaceDetails]>< [Place
2 CONC ]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the publishing of the marriage banns of [couple]
3 CONC <[Date]>< [PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF MARC
1 TYPE F
1 TITL Marriage Contract
1 ABBR Marr Contract
1 SENT [couple] signed a marriage contract< [Date]>< [PlaceDetails]>< [Place]>
2 CONC .
1 ROLE Witness
2 SENT [ThisPerson] witnessed the marriage contract of [couple]< [Date]>< [Pla
3 CONC ceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF MARL
1 TYPE F
1 TITL Marriage License
1 ABBR Marr Lic
1 SENT [couple] obtained a marriage license< [Date]>< [PlaceDetails]>< [Place]
2 CONC >.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the obtaining of the marriage license by [couple
3 CONC ]< [Date]>< [PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF MARS
1 TYPE F
1 TITL Marriage Settlement
1 ABBR Marr Settlement
1 SENT [couple] obtained a marriage settlement< [Date]>< [PlaceDetails]>< [Pla
2 CONC ce]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the marriage settlement of [couple]< [Date]>< [P
3 CONC laceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF SLGS
1 TYPE F
1 TITL LDS Seal to spouse
1 ABBR LDS SealSp
1 SENT [couple] were sealed together< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the sealing of [couple]< [Date]>< [PlaceDetails]
3 CONC >< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF RESI
1 TYPE F
1 TITL Residence (family)
1 ABBR Residence (fam)
1 SENT [couple] lived < [Desc]>< [PlaceDetails]>< [Place]>< [Date]>.
1 PLAC Y
1 DATE Y
1 DESC Y
0 _EVDEF CENS
1 TYPE F
1 TITL Census (family)
1 ABBR Census (fam)
1 SENT [couple] appeared in the census< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] appeared in the census in the household of [couple]< [Date
3 CONC ]>< [PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF Degree
1 TYPE P
1 TITL Degree
1 ABBR Degree
1 SENT [person] received a< [desc]> degree< [Date]>< [PlaceDetails]>< [Place]>
2 CONC .
1 ROLE Witness
2 SENT [ThisPerson] witnessed the degree of [person]< [Date]>< [PlaceDetails]>
3 CONC < [Place]>.
1 PLAC Y
1 DATE Y
1 DESC Y
0 _EVDEF Military
1 TYPE P
1 TITL Military
1 ABBR Military
1 SENT [person] served in the military< [Desc]>< [Date]>< [PlaceDetails]>< [Pl
2 CONC ace]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the military service of [person]< [Date]>< [Plac
3 CONC eDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC Y
0 _EVDEF Mission
1 TYPE P
1 TITL Mission
1 ABBR Mission
1 SENT [person] served a mission< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the mission of [person]< [Date]>< [PlaceDetails]
3 CONC >< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC Y
0 _EVDEF Stillborn
1 TYPE P
1 TITL Stillborn
1 ABBR Stillborn
1 SENT [person] was stillborn< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the stillbirth of [person]< [Date]>< [PlaceDetai
3 CONC ls]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF Illness
1 TYPE P
1 TITL Illness
1 ABBR Illness
1 SENT [person] was ill< with [Desc]>< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the illness of [person] with [Desc]< [Date]>< [P
3 CONC laceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC Y
0 _EVDEF Living
1 TYPE P
1 TITL Living
1 ABBR Living
1 SENT [person] was living< [Date]>< [PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF Elected
1 TYPE P
1 TITL Election
1 ABBR Elected
1 SENT [person] was elected< as [Desc]>< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the election of [person] as [Desc]< [Date]>< [Pl
3 CONC aceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC Y
0 _EVDEF Excomm
1 TYPE P
1 TITL Excommunication
1 ABBR Excomm
1 SENT [person] was excommunicated< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the excommunication of [person]< [Date]>< [Place
3 CONC Details]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF Namesake
1 TYPE P
1 TITL Namesake
1 ABBR Namesake
1 SENT [person] was named after [Desc]< [Date]>< [PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC Y
0 _EVDEF Separation
1 TYPE F
1 TITL Separation
1 ABBR Separation
1 SENT [couple] were separated< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [ThisPerson] witnessed the separation of [couple]< [Date]>< [PlaceDetai
3 CONC ls]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC N
0 _EVDEF Alt. Name
1 TYPE P
1 TITL Alternate name
1 ABBR Alt. Name
1 SENT [person] was also known as [Desc]< [Date]>.
1 PLAC N
1 DATE Y
1 DESC N
0 _EVDEF _DNA
1 TYPE P
1 TITL DNA test
1 ABBR DNA
1 SENT [person] had a DNA test performed< [Date]>.
1 PLAC N
1 DATE Y
1 DESC N
0 _EVDEF Misc
1 TYPE P
1 TITL Miscellaneous
1 ABBR Misc
1 SENT [person]< [Desc]>< [Date]>< [PlaceDetails]>< [Place]>.
1 ROLE Witness
2 SENT [person]< [Desc]>< [Date]>< [PlaceDetails]>< [Place]>.
1 PLAC Y
1 DATE Y
1 DESC Y
0 TRLR
`

**Comment by Linekio** [comment]
I think that PAF does'nt support GEDCOM 5.5.1. Anyway, I don't think there is any reason to use this software again, except to read old files.
Seems that WAC tag isn't valid in GEDCOM 5.5.1, but only in older versions. So this file is not a valid 5.5.1 file.
However, with GEDCOM, the usage is sometimes different from the specifications.
Does Rootsmagic support Gedcom file import? Could you test importing a getmyancestors file, after manually adding a WAC tag?

**Comment by sebdu66** [comment]
I install PAF just to try it.
Yes we can import a gedcom to rootsmagic.
I will try to manually add the WAC tag to a getmyancestors file

I will let you know of the result.

**Comment by sebdu66** [comment]
I add this : 
1 WAC
2 DATE 2 FEB 2019
2 STAT Completed
2 TEMP SWISS

And it's working

**Comment by sebdu66** [comment]
Ok I made the update to the python file, I export 4 generations and it works well

Is it normal that the date for lds ordinances show like this +2017-02-04 and the software doesn't reconize the date ?

**Comment by Linekio** [comment]
- On FamilySearch the date can be entered without restriction by the user, it's just a text field.
But for ordinances it's still the format "+% Y-% m-% d", I think I should just remove the "+".
- You can make a pull request
- GEDCOM 5.6 is a draft version, no software uses it. Anyway the file from Rootsmagic say "2 VERS 5.5.1"

**Comment by sebdu66** [comment]
Thanks a lot for this code and for your support.
