### ISSUE TITLE
Line wrapping

### ISSUE THREAD

**Issue by FlominatorTM** [Linekio/getmyancestors#2]
Both http://ged-inline.elasticbeanstalk.com/validate and https://chronoplexsoftware.com/gedcomvalidator/ complain about lines being too long in [steurenthaler.zip](https://github.com/Linekio/getmyancestors/files/2020246/steurenthaler.zip).

They are supposed to be wrapped with CONC tags: http://wiki-en.genealogy.net/GEDCOM/CONC-Tag

When I chop off the longer texts of the getmyancestors result file with a very lousy Python script (resulting in file [out.zip](https://github.com/Linekio/getmyancestors/files/2020245/out.zip)), then I can import the file in AhnenblattPortable, else it crashes without further notice. Ahnenblatt shows a warning about an incomplete file, but I suspect that I just broke something with my script.

Can you please do something about this?

Thanks in advance,
Flo

**Comment by Linekio** [comment]
Yes I can.
I had never found software that does not support long lines before.

2018-05-20 11:29 GMT+02:00 Florian Straub <notifications@github.com>:

**Comment by Linekio** [comment]
Done :
https://github.com/Linekio/getmyancestors/commit/cc239953941427f36052dc2c0f4e0b66f2bf7760

2018-05-20 20:12 GMT+02:00 Benoît Fontaine <benoit.fontaine.ba@gmail.com>:

**Comment by FlominatorTM** [comment]
Works like a charm. Almost all the time. Except when people write novels in a date field like happend at https://www.familysearch.org/tree/person/details/LV78-MXR
In that (very special) case no CONC is added ...

Sorry for the late reply, I wanted to find a way first, to determine where exactly the problem lies

**Comment by Linekio** [comment]
Now cut long lines on dates, urls and names: b8d011e1eea0179f28fcd0da991cb16f97de1988
