### ISSUE TITLE
FamilySearch account disabled

### ISSUE THREAD

**Issue by mhs54321** [Linekio/getmyancestors#21]
When running getmyancestors with ascent value of 6 and descent value of 7, my account was disabled, apparently for causing issues with the FamilySearch site. 

Here are the options I used,

./getmyancestors.py -a 6 -d 7 -m -u <user> -p <pass> -i <starting person ID> -o output.ged

**Comment by Linekio** [comment]
Have you received a mail from FamilySearch about that?
I never had this issue, including with a larger number of generations.
Moreover, it is not theorically possible for getmyancestors to cause problems with FamilySearch since it only read (not write).

**Comment by mhs54321** [comment]
Indeed, received email notice from FamilySearch that my account had been disabled. I can forward/share it if you want.

**Comment by Linekio** [comment]
Yes, here's my email it if you don't want to share it in public : benoitfontaine.ba@gmail.com

**Comment by mhs54321** [comment]
Yes but in my case, I don't have an LDS account.. So in this case, no
temple ordinance information was scanned / captured.

**Comment by blujio** [comment]
I’ll provide an update on my experience with this as I’m running an export for 30 generations.

jc

On Aug 26, 2019, at 10:54 AM, mhs54321 <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes but in my case, I don't have an LDS account.. So in this case, no
temple ordinance information was scanned / captured.

**Comment by Linekio** [comment]
@mhs54321 has your account been reactivated?

**Comment by mhs54321** [comment]
Not yet. Maybe there will be an answer from them soon?

>

**Comment by mhs54321** [comment]
An update.. My account has been unlocked. All is well

**Comment by Linekio** [comment]
Ok so I close this thread
