### ISSUE TITLE
Installation instructions in error

### ISSUE THREAD

**Issue by RottenRonnie** [Linekio/getmyancestors#31]
```
pi@pi4:~/tmp/getmyancestors $ python3 -m pip install -r requirements
Could not open requirements file: [Errno 2] No such file or directory: 'requirements'
```

Note that adding the complete file extension and the command carried out correctly. 
``pi@pi4:~/tmp/getmyancestors $ python3 -m pip install -r requirements.txt`
`
The READ.me file should be updated to show "python3 -m pip install -r requirements.txt" vice "python3 -m pip install -r requirements"

Thank you.

**Comment by Linekio** [comment]
close with 083843a3a0e37182377ec6f55c14504819d2a16a
