### ISSUE TITLE
"'-i' is not recognized as an internal or external command"

### ISSUE THREAD

**Issue by maikelronnau** [Linekio/getmyancestors#33]
I executed the following command in Windows using Python 3.6:

```shell
python getmyancestors.py -u <myuser> -p <mypassword> -i <myid> -a 6 -c -m -r -o results.ged
```

And got the following log with and error messages:

```
Login to FamilySearch...
'-i' is not recognized as an internal or external command,
operable program or batch file.
```

I debugged it a little bit and found out the cause being my password, which ends with an `&`. For that, `CMD` will split the commands in two thinking it's a concatenation of commands. 

I was able to run the command putting the password between quotes. I decided posting this so maybe you can add a note to the documentation warning people about that.

**Comment by Linekio** [comment]
Hello,
It's not related to  getmyancestors, but to CMD, and it's therefore in the CMD's documentation.
