### ISSUE TITLE
Feature request: Show settings somewhere

### ISSUE THREAD

**Issue by FlominatorTM** [Linekio/getmyancestors#4]
Every once in a while I would be happy to be able to see what configuration values I entered. Can you maybe either write them on the result tab or into the HEAD of the GEDCOM file?

It might also be an idea to write "getmyancestors" in the HEAD of the GEDCOM file as well

best regards and thanks for working on the script,

Flo

**Comment by Linekio** [comment]
I don't like the word "potential" since the program stops if there are no more generations to download.
That said, I'm not reluctant to change that sentence.
@changeling whats your opinion ?

**Comment by changeling** [comment]
> Every once in a while I would be happy to be able to see what configuration values I entered. Can you maybe either write them on the result tab or into the HEAD of the GEDCOM file?

I don't think that's really a good idea for the GEDCOM file itself, but it's not a bad idea to have, perhaps, a separate `<my_file>.stats` or `<my_file>.report` file or something along those lines created alongside any `<my_file>.ged`

> What about some output like "Downloading 1. of potential generations of ancestors"?

@FlominatorTM Are you referring to `getmyancestors.py` or `fstogedcom.py`? For the former case, maybe something along the lines of "Downloading 3 generations of ancestors. No descendants. Spouses and couples included. Contributors included." at the start after login?
For the latter, having those listed on the "Success!" screen? Is this what you mean? I'm attaching the current output for reference.

> It might also be an idea to write "getmyancestors" in the HEAD of the GEDCOM file as well

Looking at adding some of that in a `PR` right now. See https://github.com/Linekio/getmyancestors/pull/11

@Linekio I agree that 'potential' doesn't really fit here. I'm not sure about the rest. I'll wait for clarification. :)

<img width="686" alt="getmyancestors py output" src="https://user-images.githubusercontent.com/400894/51791694-23a96780-216c-11e9-9576-ad40c8f7ad26.png">
<img width="450" alt="fstogedcom downloading" src="https://user-images.githubusercontent.com/400894/51791617-9108c880-216b-11e9-9ce2-fd051c98c0cb.png">
<img width="444" alt="fstogedcom completed" src="https://user-images.githubusercontent.com/400894/51791618-9108c880-216b-11e9-8d2b-5c8dc8fd56f4.png">

**Comment by FlominatorTM** [comment]
Thanks for all your attention!
I was actually talking about both scripts. My problem is that I download one or two huge trees. Every once in a while it takes forever and then I would like to be able to remember what setting I used there in order to be able to speed up things next time. 

"Downloading 3 generations of ancestors. No descendants. Spouses and couples included. Contributors included" for getmyancestors.py sounds like a good idea, because it remains permanently visible in the console. I'm not sure how to achieve the same benefit in the UI version fstogedcom.py. But since I meanwhile switched to scripting my calls of getmyancestors.py the UI isn't that important to me anymore.

**Comment by changeling** [comment]
@FlominatorTM  You're very welcome! I'm enjoying working with this code, and happy that I can help with it in some way.

I'm playing with the idea of a `.settings` output file. Before I look at doing a PR, could you take a look at the output this version:

[getmyancestors.py.zip](https://github.com/Linekio/getmyancestors/files/2800454/getmyancestors.py.zip)

Backup your working copy of `getmyancestors.py`, unzip the attached file, place it in your getmyancestors.py directory and run it. Afterwards, take a look at the `.settings` file.

Look forward to your feedback.

**Comment by changeling** [comment]
@FlominatorTM This one is a bit cleaner.

[getmyancestors.py.zip](https://github.com/Linekio/getmyancestors/files/2800504/getmyancestors.py.zip)

**Comment by changeling** [comment]
OK, I've submitted PR https://github.com/Linekio/getmyancestors/pull/13 with both printing to console and creating a `.settings` file.

@FlominatorTM  if you'd like to take a look, I'd appreciate feedback on this. It's a bit different from the last, and takes the headings directly from the Help values of each setting.

[getmyancestors.py.zip](https://github.com/Linekio/getmyancestors/files/2806394/getmyancestors.py.zip)

**Comment by Linekio** [comment]
I finally decided to change the text for "Downloading 1. of generations of ancestors",
because num2words module raise a "NotImplementedError" with some languages ​​(I received today a mail from a Hungarian about that).

**Comment by FlominatorTM** [comment]
I will take a look, but it might take a few more weeks, because it's some effort (different machine that runs the newer python version ...)

**Comment by Linekio** [comment]
closed with https://github.com/Linekio/getmyancestors/pull/13
