### ISSUE TITLE
Password with various characters not accepted by CLI but accepted by GUI

### ISSUE THREAD

**Issue by bcmryan** [Linekio/getmyancestors#48]
First off, thanks for the great program!

Steps to reproduce:

Enter a password with various uppercase and lowercase letters, numerals, and special characters (specifically `^` and `$`) using the CLI parameter `-p`.

Current behavior:

A password with various uppercase and lowercase letters, numerals, and special characters (specifically `^` and `$`) produced the error `The username or password was incorrect` when used with the CLI parameter `-p`. The exact same username--password combination did not have any authentication issues when the GUI was used (`fstogedcom`).

When the password was changed on the FamilySearch website to use only uppercase and lowercase letters, neither the CLI nor the GUI produced any errors.

This may be a problem with the use of escape characters.

Expected behavior:

CLI authentication with `-p` should allow for the use of a password with various uppercase and lowercase letters, numerals, and special characters (specifically `^` and `$`) when using the CLI parameter `-p`.

**Comment by Linekio** [comment]
Hello, 
$ is a special character in bash. You need to escape with a `\`,
e.g. `-p pa\$\$word` instead of `-p pa$$word`.
