### ISSUE TITLE
FS authentication doesn't seem to be working any more

### ISSUE THREAD

**Issue by MandyShaw** [Linekio/getmyancestors#49]
Steps to reproduce: Attempt to log in to FS for getmyancestors purposes

Current behavior: Enter FamilySearch username: myusername
Enter FamilySearch password: mypassword
Login to FamilySearch... [hangs, hit CTRL+C with following results]
Traceback (most recent call last):
  File "C:\Users\shaw_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\getmyancestors\classes\session.py", line 56, in login
    idx = r.text.index('name="params" value="')
ValueError: substring not found

Expected behavior: Log in normally

Corresponding Familysearch link (optional):

I get the same problem in my own Python code which uses the same mechanism (for which many thanks). I am wondering if the relevant service has been discontinued at the FS end (see latest developer newsletter).

**Comment by grahamsedman** [comment]
I find this tool to be handy to extract my family tree from family search so I can check for errors and now can't login to family search using getmyancestors tool.  It shows ValueError: substring not found and loops this error trying to login in to family search servers.

**Comment by MandyShaw** [comment]
Yes, this Python code doesn't seem to be able to authenticate since the relevant recent changes to FS. I suspect that it uses the 'password flow' which is no longer supported; it may be that this code will need to use a formal FS application key if it is to continue.
Meanwhile, thanks for chipping in, it is good to know it's not just me!

**Comment by Linekio** [comment]
Hello,
It's now fixed with 4ba50edecd0b112c71245ea76a7e1c71eb2447ee

**Comment by grahamsedman** [comment]
Awesome work.  Thank you for sorting out the authentication and now able to create a GEDCOM file.
