### ISSUE TITLE
Google Authentication

### ISSUE THREAD

**Issue by malys** [Linekio/getmyancestors#50]
Using login with Google on Familysearch login page, it it possible to use this tool?

Is there a workaround?

Thanks

**Comment by MandyShaw** [comment]
getmyancestors doesn't use the browser and won't be able to take advantage of your having logged in there; however you can probably get what you need via https://www.familysearch.org/identity/settings/account - getmyancestors should be happy with the Username that is given there, plus its associated password (which you will need to reset if you don't know it).
