### ISSUE TITLE
Failure with errors 503 at 7th generation

### ISSUE THREAD

**Issue by ogerardin** [Linekio/getmyancestors#52]
Steps to reproduce:
getmyancestors -u ******** -p ******** -i *******,******** -a 13 -d 0 -m 

Current behavior:
Starts normally but then fails with errors 503 at 7th generation

Expected behavior:
Export all the individuals up to 13th generation as previously

Corresponding Familysearch link (optional):

**Comment by Linekio** [comment]
Hello,
503 is a server error (service unavailable) so it's a bug on the familysearch side.

**Comment by ogerardin** [comment]
Yes, that's weird, it's been like this for some time now... Do you have the same behaviour?

**Comment by Linekio** [comment]
No, this issue may be caused by a specific individual, can you identify it ?

**Comment by ogerardin** [comment]
> No, this issue may be caused by a specific individual, can you identify it ?

I'll email you with the details

**Comment by ogerardin** [comment]
As you suggested I identified the first individual that caused the error, I opened its page on familysearch.org, I saw nothing weird there, then I attempted another export and it worked! No 503 error....
Definitely something fishy there.

Anyway, if it happens to someone else, you know how to fix it now :)
