### ISSUE TITLE
Download aunts and uncles?

### ISSUE THREAD

**Issue by Froqqy54** [Linekio/getmyancestors#53]
Steps to reproduce:
None
Current behavior:
No apparent option to download brothers and sisters of ancestor

I was wondering if there's an option to download the siblings of an ancestor, I don't see any option to do so. Thank you!

**Comment by Linekio** [comment]
Hello,
You can download siblings with the `-d` option. For example, `-a 2` will download my grandfather, then `-d 1` will download his children (so my uncles and aunts) since that downloads the descendants of the entire tree.

**Comment by Froqqy54** [comment]
Thank you for the clarification! I thought that meant descendants from said person in the tree.
