### ISSUE TITLE
Invalid auth request

### ISSUE THREAD

**Issue by jrleeTS** [Linekio/getmyancestors#54]
Steps to reproduce:  
type fstogedcom in linux command window
enter familysearch userid in GUI window
enter familysearch password in GUI window
click 'sign in' button
(sometimes) it will allow entry of parameters into next GUI window, and will perform a few iterations but then it gets stuck repeating:

Current behavior:   
[2024-04-27 17:20:28]: Downloading: https://www.familysearch.org/auth/familysearch/login
[2024-04-27 17:20:29]: Downloading: https://ident.familysearch.org/login
[2024-04-27 17:20:29]: Invalid auth request
[2024-04-27 17:20:29]: Downloading: https://www.familysearch.org/auth/familysearch/login
[2024-04-27 17:20:30]: Downloading: https://ident.familysearch.org/login
[2024-04-27 17:20:30]: Invalid auth request
.
.
.

Expected behavior:  
generate gedcom file

Corresponding Familysearch link (optional):

Note:
fstogedcom worked fine for me when I last used it (same installation) two weeks ago as well as always before.  This is a new problem as of yesterday.  version 1.0.5.  I suspect the problem is with ' https://ident.familysearch.org/login ' as that appears before the 'Invalid auth request ' message and does not appear to be a valid URL--but that's just a guess.

Thanks!

**Comment by mlcarson** [comment]
I'm seeing the same thing.  I had a session going which never finished so stopped it and am now seeing this behavior.  

[2024-04-28 14:49:09]: Downloading: https://www.familysearch.org/auth/familysearch/login
[2024-04-28 14:49:09]: Downloading: https://ident.familysearch.org/login
[2024-04-28 14:49:10]: Invalid auth request
[2024-04-28 14:49:10]: Downloading: https://www.familysearch.org/auth/familysearch/login
[2024-04-28 14:49:10]: Downloading: https://ident.familysearch.org/login
[2024-04-28 14:49:10]: Invalid auth request

I can login to familysearch and don't have any messages from administrators so the account looks fine.
I didn't have logging turned on when it didn't complete but suspect this is what happened.  The app will not even start downloading now.   The only difference in my situation is that I'm using getmyancestors directly and not via fstogedcom.

**Comment by johnleuner** [comment]
Do you think this is something that could be fixed by sleeping in between requests to prevent this kind of ban?

**Comment by Linekio** [comment]
Familysearch added an anti-bot detector, I don't currently have a solution.
I don't think sleeping between requests is a solution.

**Comment by mlcarson** [comment]
This app was awesome and did exactly what I wanted before the anti-bot detector.    Now the only way of getting the same information is via rootslink and a ton of manual download requests assuming I wanted 3 gen of descendants and 6 ancestors.

They allow the following:
3 gen of descendants with 0 gen ancestors
2 gen of descendants with 2 gen ancestors
1 gen of descendants with 4 gen ancestors

I only wanted the gedcom for posting to Ancestry to assist with Thrulines and DNA matching but I'll probably just settle for a Rootslink option that's the most time efficient.

**Comment by Linekio** [comment]
However, after getting the error "Invalid auth request", it worked again for me after a few hours of waiting.

**Comment by jrleeTS** [comment]
On the basis of your last posting, Linkio, I tried fstogedcom again.  Once again it failed, but I have taken a closer look at the diagnostic output.  What I find is that things are going well until we get to an attempt to access 'memories' for Gxxx-xxB which returns an HTTP 401 'Unauthorized' code.  When that happens fstogedcom appears to get logged out and then logs back in and attempts to repeat the process.  After fourteen (14) attempts the diagnostic output begins repeating the lines I initially posted which includes the 'Invalid auth request' line.

I have some experience coding, but I am not fluent in the processes going on here.

BTAIM, when I type (Ancestor ID obfuscated): 

https://www.familysearch.org/platform/tree/persons/Gxxx-xxB/sources 

I get a valid page with source.  OTOH, when I type:

https://www.familysearch.org/platform/tree/persons/Gxxx-xxB/memories

I get '401 Unauthorized -'

It seems to me that fstogedcom is asking for something that familysearch.org does not have:  

https://www.familysearch.org/platform/tree/persons/Gxxx-xxB/memories

I think this is the relevant diagnostic output:

[2024-05-11 10:56:29]: Downloading: /platform/users/current
[2024-05-11 10:56:29]: Status code: 200
[2024-05-11 10:56:29]: Downloading: /platform/tree/persons/Gxxx-xxB/memories
[2024-05-11 10:56:29]: Status code: 401
[2024-05-11 10:56:29]: Downloading: https://www.familysearch.org/auth/familysearch/login
[2024-05-11 10:56:30]: Downloading: https://ident.familysearch.org/login

BTAIM, Gxxx-xxB has 'memories', two (2) obituariries at https://www.familysearch.org/tree/person/memories/Gxxx-xxB

**Comment by tsesani** [comment]
This is the best software for FamilySearch out there.
It allows you find and fix all errors across the entire gedcom.

I was able to download a gedcom with 2739 people seven different times today.
I get some error with memories too!
Hope this summary helps.

  13 HTTPError
5710 Status code: 200
3735 Status code: 204
  13 Status code: 403
   1 Status code: 404
   1 WARNING: /platform/memories/memories/45809817
   1 WARNING: code 403 from /platform/memories/memories/130595526 Failure in upstream call: Unable to read artifact description. (upstream 403)
   1 WARNING: code 403 from /platform/memories/memories/130595551 Failure in upstream call: Unable to read artifact description. (upstream 403)
   1 WARNING: code 403 from /platform/memories/memories/130595566 Failure in upstream call: Unable to read artifact description. (upstream 403)
   1 WARNING: code 403 from /platform/memories/memories/130595586 Failure in upstream call: Unable to read artifact description. (upstream 403)
   1 WARNING: code 403 from /platform/memories/memories/130595592 Failure in upstream call: Unable to read artifact description. (upstream 403)
   1 WARNING: code 403 from /platform/memories/memories/130595596 Failure in upstream call: Unable to read artifact description. (upstream 403)
   1 WARNING: code 403 from /platform/memories/memories/130595599 Failure in upstream call: Unable to read artifact description. (upstream 403)
   1 WARNING: code 403 from /platform/memories/memories/130595620 Failure in upstream call: Unable to read artifact description. (upstream 403)
   1 WARNING: code 403 from /platform/memories/memories/169860928 Failure in upstream call: Unable to read artifact description. (upstream 403)
   1 WARNING: code 403 from /platform/memories/memories/60077286 Failure in upstream call: Unable to read artifact description. (upstream 403)
   3 WARNING: code 403 from /platform/memories/memories/9163727 Failure in upstream call: Unable to read artifact description. (upstream 403)

**Comment by mlcarson** [comment]
It's the best software out there until it gets you banned.

**Comment by Linekio** [comment]
Hello, it's now fixed with version 1.1.0
