### ISSUE TITLE
Did some remove the 'setup.py' file?

### ISSUE THREAD

**Issue by jimlynnjulian** [Linekio/getmyancestors#56]
Steps to reproduce:

Current behavior:

Expected behavior:

Corresponding Familysearch link (optional):

**Comment by Linekio** [comment]
It was replaced by `pyproject.toml`. Just type `pip install .`.

**Comment by jimlynnjulian** [comment]
Did as you suggested. Install succeeded. Ran program successfully. No longer blocked by FS. Thanks.
