### ISSUE TITLE
Update to 5.5.1 or 7

### ISSUE THREAD

**Issue by jimlynnjulian** [Linekio/getmyancestors#58]
Steps to reproduce: standard usage

Current behavior: uses GEDCOM v5.1.1, UTF-8
UTF-8 was not introduced untill v5.5.1, according to gedcom validator program.
I examined the versions list for the gedcom spec and found there is no 5.1.1. 
Is '5.1.1' a typo?

Expected behavior: GEDCOM v5.5.1, UTF-8

Corresponding Familysearch link (optional):

**Comment by Linekio** [comment]
Hello, you're right it's a typo...

**Comment by Linekio** [comment]
fixed with 3351b5e2b0c2f6ef85d3732454ac4ea5103a664e
