### ISSUE TITLE
receive error KeyError

### ISSUE THREAD

**Issue by AdrianJSmith** [Linekio/getmyancestors#60]
Steps to reproduce:
date ; getmyancestors -o out.ged -v
Mon Jul 29 22:05:19 BST 2024
Enter FamilySearch username: myusername
Enter FamilySearch password:  mypasswd
Login to FamilySearch...
[2024-07-29 22:06:03]: Downloading: https://www.familysearch.org/auth/familysearch/login
[2024-07-29 22:06:03]: KeyError

Current behavior:

Expected behavior:

Corresponding Familysearch link (optional):

**Comment by Linekio** [comment]
Hello, it's now fixed with version 1.1.0
