### ISSUE TITLE
[feature] other way around

### ISSUE THREAD

**Issue by BenutzerEinsZweiDrei** [Linekio/getmyancestors#63]
I dont want ancestors.

I want to put the top of the ancestors tree and get his complete 500 persons family tree
.

**Comment by BenutzerEinsZweiDrei** [comment]
Is the word "progeny"?

**Comment by BenutzerEinsZweiDrei** [comment]
So 20 generations of progeny..

**Comment by Linekio** [comment]
Hey, just use `getmyancestors -i (id_of_the_top_ancestor) -d 999`
