### ISSUE TITLE
getmyancestoros.py and fstogedcom.py yield 'th' as the ordinal for all numbers.

### ISSUE THREAD

**Issue by changeling** [Linekio/getmyancestors#8]
All numbers yield as 'th' in both files as progress output..

    1th, 2th, 3th...

**Comment by Linekio** [comment]
I wonder if there is a multilingual library for ordinal numbers.
Otherwise I guess I have to change the text.

**Comment by Linekio** [comment]
Closes with 88e724d1b6d590af7dd4f7d91dbe4997bfd6a0a6
